### ISSUE TITLE
An error occurred when I was using Window subclass

### ISSUE THREAD

**Issue by HobsonCheng** [progrium/darwinkit#274]
Hi Experts,

I was trying to create a subclass of Window and override the CanBecomeKeyWindow method
```
type MyWindow struct {
	appkit.Window `objc:"NSWindow"`
}

func (w_ MyWindow) CanBecomeKeyWindow() bool {
	return true
}

func main() {
	log.Println("Program started.")

	MyWindowClass := objc.NewClass[MyWindow](
		objc.Sel("CanBecomeKeyWindow"),
	)
	objc.RegisterClass(MyWindowClass)

	app := appkit.Application_SharedApplication()

	ad := &appkit.ApplicationDelegate{}
	ad.SetApplicationDidFinishLaunching(func(foundation.Notification) {

		frame := rectOf(400, 400, 300, 200)

		win := MyWindowClass.New().InitWithContentRectStyleMaskBackingDefer(
			frame,
			appkit.WindowStyleMaskTitled|appkit.WindowStyleMaskClosable,
			appkit.BackingStoreBuffered,
			false,
		)
		objc.Retain(&win)
		win.SetTitle("Hello world")
		win.SetLevel(appkit.MainMenuWindowLevel + 2)
		win.MakeKeyAndOrderFront(nil)

		log.Println("App started.")

	})
	ad.SetApplicationShouldTerminateAfterLastWindowClosed(func(appkit.Application) bool {
		return true
	})
	app.SetDelegate(ad)
	app.SetActivationPolicy(appkit.ApplicationActivationPolicyRegular)
	app.ActivateIgnoringOtherApps(true)
	app.Run()
}

func rectOf(x, y, width, height float64) foundation.Rect {
	return foundation.Rect{Origin: foundation.Point{X: x, Y: y}, Size: foundation.Size{Width: width, Height: height}}
}
```

go run main.go
error occurred
```
2024/12/01 11:29:42 Program started.
SIGABRT: abort
PC=0x7ff8149b8102 m=0 sigcode=0
signal arrived during cgo execution

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x1005623a0, 0xc000123030)
        /usr/local/go/src/runtime/cgocall.go:158 +0x5c fp=0xc000123008 sp=0xc000122fd0 pc=0x100007edc
github.com/progrium/macdriver/objc/ffi._Cfunc_ffi_call0(0xc00006b800, 0x7ff8180ea852, 0xc0000147b0, 0xc00010d170)
        _cgo_gotypes.go:150 +0x45 fp=0xc000123030 sp=0xc000123008 pc=0x1000cb8a5
github.com/progrium/macdriver/objc/ffi.Call.func1(0xc00010d1a0?, 0x7ff800000000?, 0xc0000147b0, {0xc00010d170, 0x6, 0xc00006b800?})
        /Users/mac/Documents/sourceCode/InputBuild/3rdBase/src/github.com/progrium/macdriver/objc/ffi/ffi.go:75 +0xb1 fp=0xc000123080 sp=0xc000123030 pc=0x1000cc031
github.com/progrium/macdriver/objc/ffi.Call(0xc00006b800, 0xc00010d1a0?, 0xc0000147b0, {0xc00010d170, 0x6, 0x6})
        /Users/mac/Documents/sourceCode/InputBuild/3rdBase/src/github.com/progrium/macdriver/objc/ffi/ffi.go:75 +0x35 fp=0xc0001230d8 sp=0xc000123080 pc=0x1000cbef5
github.com/progrium/macdriver/objc.Call[...]({0x100745480, 0x7fcae1a04700}, {0x7ff834affa13}, {0xc000123258, 0x4, 0xc000123208})
        /Users/mac/Documents/sourceCode/InputBuild/3rdBase/src/github.com/progrium/macdriver/objc/call.go:61 +0x555 fp=0xc0001231c0 sp=0xc0001230d8 pc=0x10037d795
github.com/progrium/macdriver/macos/appkit.Window.InitWithContentRectStyleMaskBackingDefer({{{0x100746c60?}}}, {{0x1?, 0xc00010d0b0?}, {0xc00010d0e0?, 0xc000102240?}}, 0x2?, 0x2?, 0x0)
        /Users/mac/Documents/sourceCode/InputBuild/3rdBase/src/github.com/progrium/macdriver/macos/appkit/window.gen.go:357 +0x193 fp=0xc0001232a8 sp=0xc0001231c0 pc=0x1003630d3
main.main.func1({{0x0}})
        /Users/mac/Documents/sourceCode/InputBuild/3rdBase/src/github.com/progrium/macdriver/macos/_examples/subclass/main.go:34 +0x71 fp=0xc000123318 sp=0xc0001232a8 pc=0x100549531
github.com/progrium/macdriver/macos/appkit.(*ApplicationDelegate).ApplicationDidFinishLaunching(0x0?, {{0x100062b99?}})
        /Users/mac/Documents/sourceCode/InputBuild/3rdBase/src/github.com/progrium/macdriver/macos/appkit/application_delegate.gen.go:939 +0x23 fp=0xc000123330 sp=0xc000123318 pc=0x1002c44c3
runtime.call16(0xc00010d0b0, 0xc000014468, 0x0, 0x0, 0x0, 0x10, 0xc000123860)
        /usr/local/go/src/runtime/asm_amd64.s:724 +0x49 fp=0xc000123350 sp=0xc000123330 pc=0x100064509
runtime.reflectcall(0x100640c60?, 0x7ff7bfefda40?, 0x2?, 0x6e0db4?, 0x1?, 0x12?, 0x100640c60?)
        <autogenerated>:1 +0x3c fp=0xc000123390 sp=0xc000123350 pc=0x10006889c
reflect.Value.call({0xc00002a300?, 0xc000014468?, 0x1012a9108?}, {0x1006d6fdd, 0x4}, {0xc00010d080, 0x2, 0x100615e60?})
        /usr/local/go/src/reflect/value.go:584 +0x8c5 fp=0xc000123980 sp=0xc000123390 pc=0x100084a85
reflect.Value.Call({0xc00002a300?, 0xc000014468?, 0x13?}, {0xc00010d080?, 0x2?, 0x2?})
        /usr/local/go/src/reflect/value.go:368 +0xbc fp=0xc0001239f8 sp=0xc000123980 pc=0x100083f7c
github.com/progrium/macdriver/objc.addProtocolMethod.func1(0x100e317a0?, 0x1005cfbc0?, {0x7ff7bfefd970, 0x3, 0xc00010cf30?})
        /Users/mac/Documents/sourceCode/InputBuild/3rdBase/src/github.com/progrium/macdriver/objc/protocol.go:290 +0x2c7 fp=0xc000123aa8 sp=0xc0001239f8 pc=0x1000d9547
github.com/progrium/macdriver/objc/ffi.handleClosure(0xc00006ad00, 0x1000df748?, 0x7ff7bfefd970, 0xc0000061a0?)
        /Users/mac/Documents/sourceCode/InputBuild/3rdBase/src/github.com/progrium/macdriver/objc/ffi/ffi.go:114 +0xf0 fp=0xc000123b00 sp=0xc000123aa8 pc=0x1000cc4f0
_cgoexp_9319e47ba9ff_handleClosure(0x7ff7bfefe450?)
        _cgo_gotypes.go:228 +0x2b fp=0xc000123b30 sp=0xc000123b00 pc=0x1000cc7ab
runtime.cgocallbackg1(0x1000cc780, 0xc000123ce8?, 0x0)
        /usr/local/go/src/runtime/cgocall.go:316 +0x2b4 fp=0xc000123c00 sp=0xc000123b30 pc=0x1000083f4
runtime.cgocallbackg(0xc0000061a0?, 0x300000002?, 0xc0000061a0?)
        /usr/local/go/src/runtime/cgocall.go:235 +0x109 fp=0xc000123c90 sp=0xc000123c00 pc=0x100008089
runtime.cgocallbackg(0x1000cc780, 0x7ff7bfefd918, 0x0)
        <autogenerated>:1 +0x2f fp=0xc000123cb8 sp=0xc000123c90 pc=0x10006844f
runtime.cgocallback(0x100007f05, 0x1005623a0, 0xc000123d48)
        /usr/local/go/src/runtime/asm_amd64.s:994 +0xb4 fp=0xc000123ce0 sp=0xc000123cb8 pc=0x100065ff4
runtime.systemstack_switch()
        /usr/local/go/src/runtime/asm_amd64.s:459 fp=0xc000123ce8 sp=0xc000123ce0 pc=0x100063fc0
runtime.cgocall(0x1005623a0, 0xc000123d48)
        /usr/local/go/src/runtime/cgocall.go:168 +0x85 fp=0xc000123d20 sp=0xc000123ce8 pc=0x100007f05
github.com/progrium/macdriver/objc/ffi._Cfunc_ffi_call0(0xc00006b7a0, 0x7ff8180c8f57, 0x100e604d8, 0xc0001490e0)
        _cgo_gotypes.go:150 +0x45 fp=0xc000123d48 sp=0xc000123d20 pc=0x1000cb8a5
github.com/progrium/macdriver/objc/ffi.Call.func1(0xc0001490f0?, 0x7ff800000000?, 0x100e604d8, {0xc0001490e0, 0x2, 0xc00006b7a0?})
        /Users/mac/Documents/sourceCode/InputBuild/3rdBase/src/github.com/progrium/macdriver/objc/ffi/ffi.go:75 +0xb1 fp=0xc000123d98 sp=0xc000123d48 pc=0x1000cc031
github.com/progrium/macdriver/objc/ffi.Call(0xc00006b7a0, 0xc0001490f0?, 0x100e604d8, {0xc0001490e0, 0x2, 0x2})
        /Users/mac/Documents/sourceCode/InputBuild/3rdBase/src/github.com/progrium/macdriver/objc/ffi/ffi.go:75 +0x35 fp=0xc000123df0 sp=0xc000123d98 pc=0x1000cbef5
github.com/progrium/macdriver/objc.Call[...]({0x100744700, 0x7fcae1805d70}, {0x7ff83499418d}, {0x0, 0x0, 0x1005b91c0})
        /Users/mac/Documents/sourceCode/InputBuild/3rdBase/src/github.com/progrium/macdriver/objc/call.go:61 +0x54b fp=0xc000123ed0 sp=0xc000123df0 pc=0x1000e3b2b
github.com/progrium/macdriver/macos/appkit.Application.Run({{{0x100747e50?}}})
        /Users/mac/Documents/sourceCode/InputBuild/3rdBase/src/github.com/progrium/macdriver/macos/appkit/application.gen.go:511 +0x4d fp=0xc000123f20 sp=0xc000123ed0 pc=0x1002bf92d
main.main()
        /Users/mac/Documents/sourceCode/InputBuild/3rdBase/src/github.com/progrium/macdriver/macos/_examples/subclass/main.go:54 +0x185 fp=0xc000123f80 sp=0xc000123f20 pc=0x1005494a5
runtime.main()
        /usr/local/go/src/runtime/proc.go:250 +0x212 fp=0xc000123fe0 sp=0xc000123f80 pc=0x10003a832
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc000123fe8 sp=0xc000123fe0 pc=0x100066201

goroutine 2 [force gc (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        /usr/local/go/src/runtime/proc.go:363 +0xd6 fp=0xc00004cfb0 sp=0xc00004cf90 pc=0x10003abf6
runtime.goparkunlock(...)
        /usr/local/go/src/runtime/proc.go:369
runtime.forcegchelper()
        /usr/local/go/src/runtime/proc.go:302 +0xad fp=0xc00004cfe0 sp=0xc00004cfb0 pc=0x10003aa8d
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc00004cfe8 sp=0xc00004cfe0 pc=0x100066201
created by runtime.init.6
        /usr/local/go/src/runtime/proc.go:290 +0x25

goroutine 3 [GC sweep wait]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        /usr/local/go/src/runtime/proc.go:363 +0xd6 fp=0xc00004d790 sp=0xc00004d770 pc=0x10003abf6
runtime.goparkunlock(...)
        /usr/local/go/src/runtime/proc.go:369
runtime.bgsweep(0x0?)
        /usr/local/go/src/runtime/mgcsweep.go:278 +0x8e fp=0xc00004d7c8 sp=0xc00004d790 pc=0x100027fae
runtime.gcenable.func1()
        /usr/local/go/src/runtime/mgc.go:178 +0x26 fp=0xc00004d7e0 sp=0xc00004d7c8 pc=0x10001cc66
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc00004d7e8 sp=0xc00004d7e0 pc=0x100066201
created by runtime.gcenable
        /usr/local/go/src/runtime/mgc.go:178 +0x6b

goroutine 4 [GC scavenge wait]:
runtime.gopark(0xc000074000?, 0x100740e40?, 0x1?, 0x0?, 0x0?)
        /usr/local/go/src/runtime/proc.go:363 +0xd6 fp=0xc00004df70 sp=0xc00004df50 pc=0x10003abf6
runtime.goparkunlock(...)
        /usr/local/go/src/runtime/proc.go:369
runtime.(*scavengerState).park(0x100e31960)
        /usr/local/go/src/runtime/mgcscavenge.go:389 +0x53 fp=0xc00004dfa0 sp=0xc00004df70 pc=0x100026053
runtime.bgscavenge(0x0?)
        /usr/local/go/src/runtime/mgcscavenge.go:617 +0x45 fp=0xc00004dfc8 sp=0xc00004dfa0 pc=0x100026625
runtime.gcenable.func2()
        /usr/local/go/src/runtime/mgc.go:179 +0x26 fp=0xc00004dfe0 sp=0xc00004dfc8 pc=0x10001cc06
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc00004dfe8 sp=0xc00004dfe0 pc=0x100066201
created by runtime.gcenable
        /usr/local/go/src/runtime/mgc.go:179 +0xaa

goroutine 5 [finalizer wait]:
runtime.gopark(0x100e31d60?, 0xc000007860?, 0x0?, 0x0?, 0xc00004c770?)
        /usr/local/go/src/runtime/proc.go:363 +0xd6 fp=0xc00004c628 sp=0xc00004c608 pc=0x10003abf6
runtime.goparkunlock(...)
        /usr/local/go/src/runtime/proc.go:369
runtime.runfinq()
        /usr/local/go/src/runtime/mfinal.go:180 +0x10f fp=0xc00004c7e0 sp=0xc00004c628 pc=0x10001bd6f
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc00004c7e8 sp=0xc00004c7e0 pc=0x100066201
created by runtime.createfing
        /usr/local/go/src/runtime/mfinal.go:157 +0x45

rax    0x2000209
rbx    0x2
rcx    0x7ff7bfefd0f8
rdx    0x0
rdi    0x12
rsi    0x2
rbp    0x7ff7bfefd140
rsp    0x7ff7bfefd0f8
r8     0x6000007b48c0
r9     0x0
r10    0x0
r11    0x246
r12    0x0
r13    0x0
r14    0x12
r15    0x0
rip    0x7ff8149b8102
rflags 0x246
cs     0x7
fs     0x0
gs     0x0
exit status 2
```

**Comment by HobsonCheng** [comment]
I fixed it!
1. 
```
win := MyWindowClass.New()
win.frame = ...
win.styleMask = ...
```


2. `CanBecomeKeyWindow` => `canBecomeKeyWindow`
`MyWindowClass := objc.NewClass[MyWindow](
		objc.Sel("canBecomeKeyWindow")
)`
